// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQ1mElY-wNHwdgN12ThE_j0DPnt-yPNQ',
    appId: '1:817844794730:web:7693f576c8530113fc2113',
    messagingSenderId: '817844794730',
    projectId: 'eco-app-da818',
    authDomain: 'eco-app-da818.firebaseapp.com',
    storageBucket: 'eco-app-da818.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KDr28SFWTC6jAAQKtYxE6f0NHf_x6Mo',
    appId: '1:817844794730:android:ab2530a4f7b578dffc2113',
    messagingSenderId: '817844794730',
    projectId: 'eco-app-da818',
    storageBucket: 'eco-app-da818.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo-Ss7PS1w9brjLUjYC1Gys_Rx3_q0Dh0',
    appId: '1:817844794730:ios:7af10f70fbf1f1fbfc2113',
    messagingSenderId: '817844794730',
    projectId: 'eco-app-da818',
    storageBucket: 'eco-app-da818.appspot.com',
    iosBundleId: 'com.example.ecoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo-Ss7PS1w9brjLUjYC1Gys_Rx3_q0Dh0',
    appId: '1:817844794730:ios:7af10f70fbf1f1fbfc2113',
    messagingSenderId: '817844794730',
    projectId: 'eco-app-da818',
    storageBucket: 'eco-app-da818.appspot.com',
    iosBundleId: 'com.example.ecoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQ1mElY-wNHwdgN12ThE_j0DPnt-yPNQ',
    appId: '1:817844794730:web:c8e660d749b7a0d8fc2113',
    messagingSenderId: '817844794730',
    projectId: 'eco-app-da818',
    authDomain: 'eco-app-da818.firebaseapp.com',
    storageBucket: 'eco-app-da818.appspot.com',
  );
}
